url: https://www.cse.unsw.edu.au/~andrewb/thoughts
encoding: utf-8

markdown: kramdown

kramdown:
    typographic_symbols:
        hellip: "..."
        mdash: "---"
        ndash: "--"

    smart_quotes: ["apos", "apos", "quot", "quot"]

highlighter: rouge

exclude:
- Gemfile
- Gemfile.lock
- README.markdown

include:
- .htaccess

plugins:
